### ISSUE TITLE
Chinese translation for room expanded mod

### ISSUE THREAD

**Issue by Ventulus-lab** [pether-pg/ONI_Mods_byPether#34]
Hi Pether,
Very happy that your mod is even better. I think it might be one of the most popular mods in Steam Workshop
[roomsexpanded_zh.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/9541747/roomsexpanded_zh.zip)

**Comment by pether-pg** [comment]
Great thanks for the file!
However, recent game update might affect some of the room names. I will let you know if anything changes to the mod. If not, I will use this file :)

**Comment by pether-pg** [comment]
https://github.com/pether-pg/ONI_Mods_byPether/releases/tag/RoomsExpanded_U43beta

Due to recent changes in beta, I had to rename Kitchen to Kitchenette.
That includes all related code, in particular: keys for string translation.
You might want to update your translation to adjust for the change.

At this point I do not plan more changes to the strings, but I cannot promise Klei won't make more changes that will force me to adjust. If you want to translate stable mod version, I suggest waiting for Klei to officialy release current changes. I will understand if you decided not to provide updated translation before that

**Comment by Ventulus-lab** [comment]
Yes, I want to wait for the official version to come out and then  see what changes to the mod.

**Comment by pether-pg** [comment]
Klei made the release and if I see correctly no other room is affected.
So the only change in translation is Kitchen renamed to Kitchenette, both in strings and key IDs

**Comment by Ventulus-lab** [comment]
As far as Chinese is concerned there is little difference between Kitchen and Kitchenette. It can also be changed to "小厨房" or remain "厨房".
It seems that zh.po in "github.com/pether-pg/ONI_Mods_byPether/tree/master/UploadFiles_Steam/RoomsExpanded/Translations " is still not uploaded?
[zh.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/9811565/zh.zip)

**Comment by pether-pg** [comment]
Updated file released! Great thanks for help!
