### ISSUE TITLE
Fragrant Flowers: Critter reproduction is increased too much

### ISSUE THREAD

**Issue by nightw** [pether-pg/ONI_Mods_byPether#71]
If a critter has the Smelled Lavender effect then it will increase its reproduction by the percentage in the settings, but as a side effect the critter also "changes" the effect of its happiness bonus on reproduction to an insane to 145%/cycle. See the attached screenshots for a Drecko with the Smelled Lavender buff (total reproduction is 161%/cycle, consisting of 15% from the buff, 1.1% frin base and 145% from happiness) and without the buff (total 11% consisting of 1.1% from base and 10% from happiness). (I've deliberately changed the extra critter happiness to 0 in the settings to try to not change the happiness related reproduction to test it out, but it still caused this increase).

![20231231162945_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/220303/ea4aca77-4fa3-4c8e-a25a-7f2f474a80ae)
![20231231163039_1](https://github.com/pether-pg/ONI_Mods_byPether/assets/220303/add8bfff-8371-4df7-bd1d-1fcef411dd4c)

**Comment by pether-pg** [comment]
Fixed in 2024.3.2.1430, thanks for the report.
Please note, recent mod update introduced rebalance of default bonus value (from 5 to 1), but it might not be applied if you are not using default values. To make sure you are using default ones, please remove your settings file from mod folder, so new default one was generated
